apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nai-nfs-storage
parameters:
  dynamicProv: ENABLED
  nfsServer: PLACEHOLDER
  nfsServerName: PLACEHOLDER
  storageType: NutanixFiles
provisioner: csi.nutanix.com
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
