apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-remove-exclude-lb-label
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metallb-remove-exclude-lb-label
rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metallb-remove-exclude-lb-label
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metallb-remove-exclude-lb-label
subjects:
  - kind: ServiceAccount
    name: metallb-remove-exclude-lb-label
    namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: metallb-remove-exclude-lb-label
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      serviceAccountName: metallb-remove-exclude-lb-label
      restartPolicy: Never
      containers:
        - name: remove-label
          image: docker.io/mesosphere/kubectl:v1.34.1-alpine
          command:
            - /bin/sh
            - -c
            - |
              kubectl label nodes --all \
                node.kubernetes.io/exclude-from-external-load-balancers- \
                --overwrite
