apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - cnpg-cluster.yaml
  - schedulebackup.yaml
  - ../../../templates/nai-db

nameSuffix: -dc01

patches:
  - path: patch.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: nai-db
      namespace: nai-db
